spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms  # 연결 타임아웃
      lettuce:
        pool:
          max-active: 10  # 최대 활성 연결 수
          max-idle: 5  # 최대 유휴 연결 수
          min-idle: 1  # 최소 유휴 연결 수
          max-wait: 2000ms  # 최대 대기 시간

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 30분
  refresh-expiration : ${JWT_REFRESH_EXPIRATION} # 7일

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG

springdoc:
  packages-to-scan: com.dao.nbti
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

openai:
  api-key: ${API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: dao-nbti

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always