apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  MYSQL_DATABASE: "nbti"
  DB_PORT: "3308"
  DB_URL: "jdbc:mariadb://db:3306/nbti"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  JWT_EXPIRATION: "18000000"
  JWT_REFRESH_EXPIRATION: "604800000"

  env.js: |
    window.env = {
        VITE_API_BASE_URL: "/boot"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      tcp {
        host => "0.0.0.0"
        port => 5000
        codec => json_lines
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "nbti-%{+YYYY.MM.dd}"
        ilm_enabled => false
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.basePath: "/kibana"
    server.rewriteBasePath: true
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
